# Generated by Django 4.1.5 on 2023-02-08 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('date_published', models.DateTimeField(blank=True, null=True)),
                ('query_str', models.CharField(blank=True, max_length=250, null=True)),
                ('snippet', models.TextField(blank=True, null=True)),
                ('web_url', models.URLField(blank=True, null=True)),
                ('image_url', models.URLField(blank=True, null=True)),
                ('image_ratio_wh', models.DecimalField(decimal_places=2, max_digits=4)),
                ('status', models.CharField(choices=[('A', 'Approved'), ('R', 'Reviewing')], default='R', max_length=3)),
                ('image_fit', models.CharField(choices=[('F', 'Fit'), ('D', 'Distorted')], default='D', max_length=1)),
            ],
            options={
                'db_table': 'news',
                'managed': True,
            },
        ),
    ]
